[package]
name = "lark-cli"
version = "0.1.0"
authors = [
    "Jonathan Turner <jonathan.d.turner@gmail.com>",
    "Yehuda Katz <wycats@gmail.com>",
    "Niko Matsakis <niko@alum.mit.edu>"
]
edition = "2018"

[dependencies]
derive-new = "0.5.5"
derive_more = "0.12.0"
lazy_static = "1.1.0"
log = "0.4.5"
generational-arena = "0.1.0"
parking_lot = "0.6.4"
seahash = "3.0.5"
smart-default = "0.2.0"
typed-arena = "1.4"
unicode-xid = "0.1.0"
itertools = "0.7.8"
text-diff = "0.4.0"
languageserver-types = "0.51.0"
flexi_logger = "0.9.2"
pretty_env_logger = "0.2"
salsa = "0.8"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
url = "1.7"

lark-build = { path = "../lark-build" }
lark-collections = { path = "../lark-collections" }
lark-debug-derive = { path = "../lark-debug-derive" }
lark-debug-with = { path = "../lark-debug-with" }
lark-entity = { path = "../lark-entity" }
lark-error = { path = "../lark-error" }
lark-eval = { path = "../lark-eval" }
lark-hir = { path = "../lark-hir" }
lark-indices = { path = "../lark-indices" }
lark-intern = { path = "../lark-intern" }
lark-language-server = { path = "../lark-language-server" }
lark-mir = { path = "../lark-mir" }
lark-parser = { path = "../lark-parser" }
lark-query-system = { path = "../lark-query-system" }
lark-span = { path = "../lark-span" }
lark-string = { path = "../lark-string" } 
lark-task-manager = { path = "../lark-task-manager" }
lark-ty = { path = "../lark-ty" }
lark-type-check = { path = "../lark-type-check" }
lark-unify = { path = "../lark-unify" }
language-reporting = { git = "https://github.com/nikomatsakis/language-reporting", branch = "remove-codespan-dep" }

termcolor = "1.0.4"
