[package]
name = "lark-task-manager"
version = "0.1.0"
authors = ["Jonathan Turner <jonathan.d.turner@gmail.com>"]
edition = "2018"

[dependencies]
languageserver-types = "0.51.0"
lark-collections = { path = "../lark-collections" }
lark-mir = { path = "../lark-mir" }
url = "1.7"