language: rust
rust:
  - nightly-2018-10-30
  - nightly
cache:
- cargo
script:
- RUST_BACKTRACE=1 CARGO_INCREMENTAL=0 cargo test --all
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
  
