[package]
name = "lark"
version = "0.1.0"
authors = [
    "Jonathan Turner <jonathan.d.turner@gmail.com>",
    "Yehuda Katz <wycats@gmail.com>",
    "Niko Matsakis <niko@alum.mit.edu>"
]
edition = '2018'

[workspace]

[dependencies]
codespan = "0.1.3"
codespan-reporting = "0.1.4"
derive-new = "0.5.5"
derive_more = "0.12.0"
lazy_static = "1.1.0"
log = "0.4.5"
generational-arena = "0.1.0"
parking_lot = "0.6.4"
seahash = "3.0.5"
smart-default = "0.2.0"
typed-arena = "1.4"
unicode-xid = "0.1.0"
itertools = "0.7.8"
text-diff = "0.4.0"
languageserver-types = "0.51.0"
salsa = "0.6.0"

debug = { path = "components/debug" }
indices = { path = "components/indices" }
intern = { path = "components/intern" }
hir = { path = "components/hir" }
lark-codegen = { path = "components/lark-codegen" }
lark-debug-derive = { path = "components/lark-debug-derive" }
lark-eval = { path = "components/lark-eval" }
lark-language-server = { path = "components/lark-language-server" }
lark-mir = { path = "components/lark-mir" }
lark-query-system = { path = "components/lark-query-system" }
lark-string = { path = "components/lark-string" } 
lark-task-manager = { path = "components/lark-task-manager" }
map = { path = "components/map" }
parser = { path = "components/parser" }
ty = { path = "components/ty" }
type-check = { path = "components/type-check" }
unify = { path = "components/unify" }

[dev-dependencies]
unindent = "0.1.3"
language-reporting = { git = "https://github.com/wycats/language-reporting.git" }
termcolor = "1.0.4"
pretty_env_logger = "0.2"
