[package]
name = "lark"
version = "0.1.0"
authors = [
    "Jonathan Turner <jonathan.d.turner@gmail.com>",
    "Yehuda Katz <wycats@gmail.com>",
    "Niko Matsakis <niko@alum.mit.edu>"
]
edition = '2018'

[dependencies]
codespan = "0.1.3"
codespan-reporting = "0.1.4"
derive-new = "0.5.5"
derive_more = "0.12.0"
lalrpop-util = "0.16.0"
lazy_static = "1.1.0"
log = "0.4.5"
indexed_vec = "1.1.1"
indexmap = "1.0.0"
generational-arena = "0.1.0"
parking_lot = "0.6.4"
rustc-hash = "1.0"
seahash = "3.0.5"
smart-default = "0.2.0"
typed-arena = "1.4"
unicode-xid = "0.1.0"
itertools = "0.7.8"
text-diff = "0.4.0"
languageserver-types = "0.51.0"
salsa = "0.3.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
unindent = "0.1.3"
language-reporting = { git = "https://github.com/wycats/language-reporting.git" }
termcolor = "1.0.4"
pretty_env_logger = "0.2"
