[package]
name = "lark-span"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>"]
edition = "2018"

[dependencies]
derive-new = "0.5.5"
lark-debug-derive = { path = "../lark-debug-derive" }
lark-string = { path = "../lark-string" }
debug = { path = "../debug" }
