[package]
name = "lark-collections"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
rustc-hash = "1.0"
indexmap = "1.0.2"
lark-debug-with = { path = "../lark-debug-with" }