[package]
name = "lark-intern"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
lark-collections = { path = "../lark-collections" }
lark-indices = { path = "../lark-indices" }
parking_lot = "0.7"