[package]
name = "unify"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
debug = { path = "../debug" }
lark-debug-derive = { path = "../lark-debug-derive" }
indices = { path = "../indices" }