[package]
name = "lark-test"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
ast = { path = "../ast" }
debug = { path = "../debug" }
diff = "0.1.0"
env_logger = "0.5.13"
lark-error = { path = "../lark-error" }
lark-hir = { path = "../lark-hir" }
lark-query-system = { path = "../lark-query-system" }
lark-parser = { path = "../lark-parser" }
lark-string = { path = "../lark-string" }
lark-seq = { path = "../lark-seq" }
intern = { path = "../intern" }
salsa = "0.8.0"
