[package]
name = "lark-test"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
diff = "0.1.0"
env_logger = "0.5.13"
lark-debug-with = { path = "../lark-debug-with" }
lark-error = { path = "../lark-error" }
lark-hir = { path = "../lark-hir" }
lark-intern = { path = "../lark-intern" }
lark-query-system = { path = "../lark-query-system" }
lark-parser = { path = "../lark-parser" }
lark-seq = { path = "../lark-seq" }
lark-span = { path = "../lark-span" }
lark-string = { path = "../lark-string" }
lark-collections = { path = "../lark-collections" }
lazy_static = "1.2.0"
rayon = "1.0.3"
regex = "1"
salsa = "0.8.0"
walkdir = "2.2.7"
