[package]
name = "lark-ty"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
derive-new = "0.5.5"
parking_lot = "0.6.4"

ast = { path = "../ast" }
debug = { path = "../debug" }
indices = { path = "../indices" }
intern = { path = "../intern" }
map = { path = "../map" }
lark-debug-derive = { path = "../lark-debug-derive" }
lark-error = { path = "../lark-error" }
lark-entity = { path = "../lark-entity" }
lark-string = { path = "../lark-string" }
parser = { path = "../parser" }
lark-unify = { path = "../lark-unify" }