[package]
name = "lark-type-check"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
derive-new = "0.5.5"
generational-arena = "0.1.0"
indices = { path = "../indices" }
intern = { path = "../intern" }
debug = { path = "../debug" }
lark-error = { path = "../lark-error" }
lark-entity = { path = "../lark-entity" }
lark-hir = { path = "../lark-hir" }
lark-parser = { path = "../lark-parser" }
lark-ty = { path = "../lark-ty" }
lark-unify = { path = "../lark-unify" }
log = "0.4.5"
map = { path = "../map" }
salsa = "0.8"
