[package]
name = "lark-type-check"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
generational-arena = "0.1.0"
log = "0.4.5"
salsa = "0.6.2"

ast = { path = "../ast" }
hir = { path = "../hir" }
indices = { path = "../indices" }
intern = { path = "../intern" }
lark-error = { path = "../lark-error" }
lark-entity = { path = "../lark-entity" }
map = { path = "../map" }
parser = { path = "../parser" }
lark-ty = { path = "../lark-ty" }
lark-unify = { path = "../lark-unify" }
