[package]
name = "lark-type-check"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
derive-new = "0.5.5"
ast = { path = "../ast" }
generational-arena = "0.1.0"
hir = { path = "../hir" }
indices = { path = "../indices" }
intern = { path = "../intern" }
lark-error = { path = "../lark-error" }
lark-entity = { path = "../lark-entity" }
lark-ty = { path = "../lark-ty" }
lark-unify = { path = "../lark-unify" }
log = "0.4.5"
map = { path = "../map" }
parser = { path = "../parser" }
salsa = "0.7"
